apiVersion: core.matrixorigin.io/v1alpha1
kind: LogSet
metadata:
  name: logset
spec:
  image: aylei/mo-service:v0.6.0-alpha1
  replicas: 3
  sharedStorage:
    s3:
      path: test/bucket
  volume:
    size: 10Gi
    storageClassName: gp2
  resources:
    requests:
      cpu: 1
  initialConfig:
    logShards: 1
    dnShards: 1
    haKeeperReplicas: 3
    logShardReplicas: 3
