apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
spec:
  imageRepository: matrixorigin/matrixone
  version: nightly-63835b83
  logService:
    replicas: 3
    sharedStorage:
      s3:
        path: maomao-moc-test/test
        secretRef:
          name: aws
    volume:
      size: 10Gi
  tn:
    replicas: 1
    # cacheVolume specifies a dedicated volume for TN's local cache
    cacheVolume:
      size: 10Gi
  cnGroups:
  - name: tp
    replicas: 2
    cacheVolume:
      size: 10Gi
